javac -d . Process.java
javac -d . Query.java
javac -d . Relation.java
javac -d . DataOperation.java
javac -d . Display.java
javac -d . Database.java
javac -d . Select.java
javac -d . Do.java
javac -d . Create.java
javac -d . Use.java
javac -d . QueryCheck.java
javac -d . QueryManagement.java
javac -d . Elsql_Core.java
javac -d . Console.java